#Napiši program koji će sva slova"a" zamijeniti slovom "b", a sva slova "b" zamijeniti slovom "a" (nije potrebno razlikovati mala i velika slova)
n=input("upiši rečenicu:")
n=n.replace("b","x")
n=n.replace("B","X")
n=n.replace("a","b")
n=n.replace("A","B")
n=n.replace("x","a")
n=n.replace("X","A")
print(n)
